version: '3'
services:
  search:
    volumes:
     - /home/suijhin/tagalys/Search/fashion-clip:/workspace
    build:
      context: .
      dockerfile: Dockerfile
    ports:
     - 5000:5000
     - 8888:8888
    stdin_open: true
    tty: true
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
